/* ============================================================ COPY ============================================================ */
var AREAS = [
  {id:"web",   glyph:"wave",  nl:"Software & web",   en:"Software & web"},
  {id:"proto", glyph:"frame", nl:"Engineering & prototyping", en:"Engineering & prototyping"},
  {id:"make",  glyph:"turn",  nl:"Productie",        en:"Manufacturing"},
  {id:"yard",  glyph:"shed",  nl:"Project Yard",     en:"Project Yard"},
  {id:"start", glyph:"vector",nl:"Start-up support", en:"Start-up support"}
];
var TOPROW = 3;
var FORMS = {
  nl:"https://docs.google.com/forms/d/e/1FAIpQLSdeJxAmT8HDOpLdU8Btsm11Axnidh0sK7JIV5eqvxPnAKQYxA/viewform",
  en:"https://docs.google.com/forms/d/e/1FAIpQLScyRzXrcnD57-Fo27h5iNfAS59IsyiOmTJ825Avvrt87ieJWA/viewform"
};


/* ============================================================ EXPERIENCE
   Engineering work behind the two public websites. Clients under NDA are described
   by what was built, never by who paid for it. `areas` decides which activity pages
   each item appears on.
   ============================================================ */
var EXPERIENCE = [
  {id:"acoustic", img:"domain-data", areas:["proto","start"],
   t:{nl:"Akoestische dronedetectie",en:"Acoustic drone detection"},
   k:{nl:"Onderzoek + hardwarespec",en:"Research + hardware spec"},
   p:{nl:"Een gesynchroniseerde microfoonarray die drones detecteert, classificeert en lokaliseert. Wij deden het onderzoek, de systeemarchitectuur, de hardwarespecificatie en de onderdelenlijst voor de eerste bouw in Nederland.",
      en:"A synchronised microphone array that detects, classifies and locates drones. We did the research, the system architecture, the hardware specification and the bill of materials for the first build in the Netherlands."},
   m:{nl:"Onder geheimhouding",en:"Under NDA"}},
  {id:"rtk", img:"domain-drone", areas:["proto","make"],
   t:{nl:"RTK-positionering voor een drone",en:"RTK positioning for a drone"},
   k:{nl:"Integratie + firmware",en:"Integration + firmware"},
   p:{nl:"Centimeterpositionering aan boord: een dual-band RTK-ontvanger gekoppeld aan een vluchtcontroller, inclusief de correctiestroom en de brug ertussen. Van losse modules naar een werkend geheel.",
      en:"Centimetre-level positioning on board: a dual-band RTK receiver tied to a flight controller, including the correction stream and the bridge between them. From loose modules to a working whole."},
   m:{nl:"Vliegend getest",en:"Flight tested"}},
  {id:"wearable", img:"exp-wearable", areas:["proto","start"],
   t:{nl:"Draagbare alarmknop",en:"Wearable alarm device"},
   k:{nl:"Haalbaarheid + fasering",en:"Feasibility + phasing"},
   p:{nl:"Een start-up wilde een alarmarmband die zonder telefoon werkt — in sieraadformaat. De eerste vraag was niet hoe, maar of het past: radio, antenne en accu in die maat. We deden de haalbaarheid en stelden een goedkoper prototype voor eerst, zodat het dure deel pas betaald hoeft te worden als het idee klopt.",
      en:"A start-up wanted an alarm bracelet that works without a phone — at jewellery scale. The first question wasn't how but whether it fits: radio, antenna and battery in that volume. We did the feasibility and proposed a cheaper prototype first, so the expensive part only gets paid for once the idea holds up."},
   m:{nl:"Fase 1 gedefinieerd",en:"Phase 1 defined"}},
  {id:"mech", img:"domain-mech", areas:["make","proto"],
   k:{nl:"Constructie + fabricage",en:"Structure + fabrication"},
   t:{nl:"Draagconstructie op een voertuig",en:"Vehicle-mounted structure"},
   p:{nl:"Een railsysteem op een autodak dat een zware, bewegende last moet dragen en bij snelheid stabiel moet blijven. Berekening, CAD, en onderdelen die met de machines hier gemaakt konden worden.",
      en:"A rail system on a car roof carrying a heavy moving load that has to stay stable at speed. Calculation, CAD, and parts that could be made on the machines here."},
   m:{nl:"Onder geheimhouding",en:"Under NDA"}},
  {id:"inspect", img:"exp-inspect", areas:["proto","start"],
   t:{nl:"Inspectiedrone voor leidingen",en:"Pipeline inspection drone"},
   k:{nl:"Scope + planning",en:"Scope + planning"},
   p:{nl:"Vóór er iets gebouwd wordt: wat moet het ding kunnen, in welke leidingen, bij welke druk, en wat kost dat aan tijd. Een plan waar een opdrachtgever een besluit op kan nemen in plaats van een offerte met aannames.",
      en:"Before anything gets built: what the thing has to do, in which pipes, at what pressure, and what that costs in time. A plan a client can decide on, rather than a quote full of assumptions."},
   m:{nl:"In uitvoering",en:"In progress"}}
];

var EXPH={
  h:{nl:"Ervaring",en:"Experience"},
  d:{nl:"Werk dat we op dit terrein gedaan hebben.",
     en:"Work we've done in this area."},
  none:{nl:"Wilt u de volgende zijn?",en:"Would you like to be next?"},
  engh:{nl:"Engineering",en:"Engineering"},
  engd:{nl:"Wat er gebouwd is, niet voor wie.",
        en:"What was built, not who paid for it."}
};


/* ============================================================ DISCIPLINES
   What "engineering" actually means here. Shown on the Prototyping page.
   `ic` is a key in the ICON set (src/drawings.js).
   ============================================================ */
var DISCIPLINES = {
  h:{nl:"Welke technische vakgebieden we dekken",en:"The engineering domains we cover"},
  d:{nl:"\u201CEngineering\u201D zegt weinig. Dit zijn de vakgebieden die we zelf in huis hebben, met bij elk een voorbeeld van werk dat we erin gedaan hebben. Waarom dat uitmaakt: een prototype dat over vier partijen verdeeld wordt, wordt vier keer opnieuw uitgelegd.",
     en:"\u201CEngineering\u201D says very little. These are the domains we cover ourselves, each with an example of work we have done in it. Why that matters: a prototype split across four suppliers gets explained four times over."},
  items:[
    {ic:"mech", t:{nl:"Werktuigbouw",en:"Mechanical engineering"},
     p:{nl:"Constructie, sterkte en beweging. Wat moet het dragen, hoe stijf moet het zijn, en waar gaat het stuk als het valt.",
        en:"Structure, strength and motion. What it has to carry, how stiff it must be, and where it fails when it's dropped."},
     ex:{nl:"Een railsysteem op een autodak dat een zware, bewegende last draagt en bij snelheid stabiel blijft.",
         en:"A roof rail system carrying a heavy moving load that stays stable at speed."},
     dw:"gears", note:{nl:"Render — de draagconstructie op het dak",en:"Render — the roof structure"},
     k:"CAD · FEM · tolerantie"},
    {ic:"cad", t:{nl:"CAD en ontwerp",en:"CAD and design"},
     p:{nl:"Van schets naar tekening waar een machine mee overweg kan. Inclusief de tekeningen die een leverancier nodig heeft.",
        en:"From sketch to a drawing a machine can work from, including the drawings a supplier needs."},
     ex:{nl:"Een gefreesde beugel met boorpatroon en toleranties, zo getekend dat de verspaner niets hoefde te vragen.",
         en:"A machined bracket with hole pattern and tolerances, drawn so the machinist had nothing to ask."},
     dw:"part", note:{nl:"Render — de gefreesde beugel",en:"Render — the machined bracket"},
     k:"SolidWorks · STEP · 2D"},
    {ic:"elec", t:{nl:"Elektronica",en:"Electronics"},
     p:{nl:"Voeding, sensoren, motoren en alles wat daar tussen moet. Meten waarom iets niet doet wat het hoort te doen.",
        en:"Power, sensors, motors and everything in between. Measuring why something isn't doing what it should."},
     ex:{nl:"Meten waarom een sensorsignaal wegviel bij koude \u2014 en het opgelost met voeding, niet met software.",
         en:"Measuring why a sensor signal dropped out in the cold \u2014 and fixing it in the power supply, not the software."},
     dw:"pcb", note:{nl:"Foto — de meetbank in bedrijf",en:"Photo — the measurement bench in use"},
     k:"analoog · vermogen · meten"},
    {ic:"pcb", t:{nl:"PCB-ontwerp",en:"PCB design"},
     p:{nl:"Schema en print, van eenvoudige tweelaags tot ontwerpen waar layout en storing echt uitmaken.",
        en:"Schematic and board, from simple two-layer up to designs where layout and noise genuinely matter."},
     ex:{nl:"Schema en print voor een meetkaart met gesynchroniseerde kanalen, waar layout het verschil maakte.",
         en:"Schematic and board for a measurement card with synchronised channels, where layout made the difference."},
     dw:"pcb", note:{nl:"Render — de print, schuin van boven",en:"Render — the board, three-quarter view"},
     k:"schema · layout · BOM"},
    {ic:"firmware", t:{nl:"Firmware en embedded",en:"Firmware and embedded"},
     p:{nl:"De code die op het ding zelf draait: C/C++ op microcontrollers, drivers, communicatie en opstarten zonder verrassingen.",
        en:"The code that runs on the thing itself: C/C++ on microcontrollers, drivers, comms, and starting up without surprises."},
     ex:{nl:"De brug tussen een RTK-ontvanger en een vluchtcontroller: correctiestroom in, positie uit, zonder haperen.",
         en:"The bridge between an RTK receiver and a flight controller: corrections in, position out, without stutter."},
     dw:"signal", note:{nl:"Foto — scherm met firmware en een debugger",en:"Photo — screen with firmware and a debugger"},
     k:"C/C++ · RTOS · drivers"},
    {ic:"control", t:{nl:"Besturing en regeltechniek",en:"Control engineering"},
     p:{nl:"Regelkringen die stabiel blijven als de werkelijkheid afwijkt van het model. Positie, snelheid, temperatuur, kracht.",
        en:"Control loops that stay stable when reality departs from the model. Position, speed, temperature, force."},
     ex:{nl:"Een achtervolgingsregelaar die een bewegend doel volgt terwijl het platform zelf ook beweegt.",
         en:"A pursuit controller that tracks a moving target while the platform itself is moving too."},
     dw:"gears", note:{nl:"Render — de aandrijving in beweging",en:"Render — the drive in motion"},
     k:"PID · state · tuning"},
    {ic:"robot", t:{nl:"Robotica en mechatronica",en:"Robotics and mechatronics"},
     p:{nl:"Waar mechanica, elektronica en software \u00e9\u00e9n systeem worden. Aandrijving, terugkoppeling en veiligheid.",
        en:"Where mechanics, electronics and software become one system. Drives, feedback and safety."},
     ex:{nl:"Aandrijving, terugkoppeling en noodstop van een mechanisme dat op een rijdend voertuig werkt.",
         en:"Drive, feedback and emergency stop for a mechanism operating on a moving vehicle."},
     dw:"cnc", note:{nl:"Foto — het mechanisme op de bank",en:"Photo — the mechanism on the bench"},
     k:"actuatie · feedback"},
    {ic:"drone", t:{nl:"Drones en UAV",en:"Drones and UAV"},
     p:{nl:"Frames, vluchtcontrollers, positionering en payloads. Inclusief wat er nodig is om er legaal mee te vliegen.",
        en:"Frames, flight controllers, positioning and payloads. Including what it takes to fly one legally."},
     ex:{nl:"Centimeterpositionering aan boord van een drone: dual-band RTK gekoppeld aan de vluchtcontroller, vliegend getest.",
         en:"Centimetre positioning on board a drone: dual-band RTK tied to the flight controller, flight tested."},
     dw:"drone", note:{nl:"Render — het droneframe",en:"Render — the drone frame"},
     k:"ArduPilot · RTK · payload"},
    {ic:"data", t:{nl:"Signalen en data",en:"Signals and data"},
     p:{nl:"Metingen omzetten in iets waar een besluit op kan: filteren, karakteriseren, en zeggen hoe zeker het antwoord is.",
        en:"Turning measurements into something you can decide on: filtering, characterising, and saying how certain the answer is."},
     ex:{nl:"Een gesynchroniseerde microfoonarray die drones detecteert, classificeert en lokaliseert \u2014 inclusief hoe zeker dat antwoord is.",
         en:"A synchronised microphone array that detects, classifies and locates drones \u2014 including how certain that answer is."},
     dw:"signal", note:{nl:"Render — de microfoonarray",en:"Render — the microphone array"},
     k:"Python · DSP · analyse"},
    {ic:"dfm", t:{nl:"Ontwerpen voor productie",en:"Design for manufacturing"},
     p:{nl:"Een prototype dat niet te maken is, is geen prototype. We ontwerpen naar het proces dat het uiteindelijk maakt.",
        en:"A prototype that can't be made isn't a prototype. We design towards the process that will eventually make it."},
     ex:{nl:"Een draagbaar alarmapparaat in sieraadformaat: eerst uitgerekend of radio, antenne en accu er \u00fcberhaupt in passen.",
         en:"A wearable alarm device at jewellery scale: first working out whether radio, antenna and battery fit at all."},
     dw:"rule", note:{nl:"Render — hetzelfde onderdeel, geprint en gefreesd",en:"Render — the same part, printed and milled"},
     k:"DFM · kostprijs · serie"},
    {ic:"test", t:{nl:"Testen en validatie",en:"Testing and validation"},
     p:{nl:"Bewijzen dat het werkt, niet hopen. Testopstellingen, meetplannen en een eerlijk verslag als het tegenvalt.",
        en:"Proving it works rather than hoping. Test rigs, measurement plans, and an honest report when it disappoints."},
     ex:{nl:"Een meetplan voor een inspectiedrone: welke leidingen, welke druk, en wat er gemeten moet worden om iets te kunnen zeggen.",
         en:"A measurement plan for an inspection drone: which pipes, what pressure, and what has to be measured to conclude anything."},
     dw:"valve", note:{nl:"Foto — de testopstelling",en:"Photo — the test rig"},
     k:"rigs · meetplan · rapport"},
    {ic:"print3d", t:{nl:"Maken in huis",en:"Making it here"},
     p:{nl:"3D-print, lasersnijden en kleine CNC staan bij ons. Een ontwerpfout op dinsdag is woensdag een nieuw onderdeel.",
        en:"3D printing, laser cutting and small CNC are ours. A design mistake on Tuesday is a new part on Wednesday."},
     ex:{nl:"Een jig om honderd identieke onderdelen uit te lijnen \u2014 getekend, geprint en gebruikt zonder dat er een leverancier aan te pas kwam.",
         en:"A jig to align a hundred identical parts \u2014 drawn, printed and in use without a supplier in the loop."},
     dw:"printer", note:{nl:"Foto — een onderdeel halverwege de printer",en:"Photo — a part halfway through the printer"},
     k:"FDM · laser · CNC"}
  ],
  shots:[
    {t:{nl:"Foto — de bank",en:"Photo — the bench"},s:{nl:"Solderen of meten · 4:3",en:"Soldering or measuring · 4:3"}},
    {t:{nl:"Foto — een onderdeel",en:"Photo — a part"},s:{nl:"Net van de printer · 4:3",en:"Fresh off the printer · 4:3"}},
    {t:{nl:"Foto — CAD op het scherm",en:"Photo — CAD on screen"},s:{nl:"Over de schouder · 4:3",en:"Over the shoulder · 4:3"}}
  ]
};

var C = {
home:{
  tagline:{nl:"Make non-existent reality", en:"Make non-existent reality"},
  scroll:{nl:"Scroll", en:"Scroll"},
  blocksh:{nl:"Wat we doen", en:"What we do"},
  blocksd:{nl:"Vijf richtingen, één team. Software aan de ene kant, hardware aan de andere, en dezelfde mensen aan allebei.",
           en:"Five directions, one team. Software on one side, hardware on the other, and the same people across both."},
  blurbs:{
    web:{nl:"Website, webshop, app, AI, SEO, automatisering. U beschrijft wat u wilt bereiken, wij kiezen samen de beste uitvoering.",
         en:"Website, online shop, app, AI, SEO, automation. You describe what you want to achieve, we pick the best execution together."},
    proto:{nl:"U heeft een idee; wij bouwen het. Mechanica, elektronica, firmware en besturing in één team, van schets tot werkend exemplaar.",
           en:"You have an idea; we build it. Mechanics, electronics, firmware and control in one team, from sketch to working unit."},
    make:{nl:"Het verlengstuk van prototyping: kleine series per stuk, zonder minimale afname. Grotere aantallen begeleiden we naar een producent.",
          en:"The extension of prototyping: small runs priced per part, with no minimum order. Larger volumes we manage for you, through a manufacturer."},
    yard:{nl:"Een werkplaats voor de regio, waar bedrijven, studenten en makers samen bouwen. In opbouw.",
          en:"A workshop for the region, where companies, students and makers build together. In development."},
    start:{nl:"U heeft een idee en geen technisch team. Wij zijn dat team, tot u er zelf een heeft.",
           en:"You have an idea and no technical team. We are that team, until you have your own."}
  },
  more:{nl:"Bekijken", en:"View"},
  /* the one fact per area that makes someone click. Sourced where it's a number. */
  hooks:{
    web:{nl:"Zeven op de tien mkb-bedrijven heeft een website, maar bij veel bedrijven is die jaren oud en levert hij niets op.",
         en:"Seven in ten SMEs have a website, but for many it is years old and brings in nothing."},
    proto:{nl:"De meeste bureaus doen \u00f3f elektronica, \u00f3f mechanica, \u00f3f industrieel ontwerp. Wij doen het in \u00e9\u00e9n team, op mkb-schaal.",
           en:"Most studios do either electronics, or mechanics, or industrial design. We do all of it in one team, at SME scale."},
    make:{nl:"Onder een paar honderd stuks wint Nederland bijna altijd van India. Wij rekenen het voor en zeggen het eerlijk.",
          en:"Below a few hundred units the Netherlands almost always beats India. We do the maths and say so."},
    yard:{nl:"Brabant telt 22.805 bedrijven met twee of meer medewerkers in onze sectoren, en ruim 30.000 technische studenten. Die groepen komen elkaar nauwelijks tegen.",
          en:"Brabant has 22,805 companies with two or more staff in our sectors, and over 30,000 engineering students. Those groups barely meet."},
    start:{nl:"Eerst haalbaarheid, dan pas bouwen \u2014 zodat het dure deel pas betaald wordt als het idee klopt.",
           en:"Feasibility first, building second \u2014 so the expensive part is only paid for once the idea holds up."}
  },
  shots:{
    web:{nl:"Foto \u2014 scherm met een site in aanbouw",en:"Photo \u2014 screen with a site being built"},
    proto:{nl:"Foto \u2014 onderdeel halverwege de printer",en:"Photo \u2014 part halfway through the printer"},
    make:{nl:"Foto \u2014 onderdelen uit de lasersnijder",en:"Photo \u2014 parts out of the laser cutter"},
    yard:{nl:"Foto \u2014 een lege ruimte of een volle werkbank",en:"Photo \u2014 an empty space or a full bench"},
    start:{nl:"Foto \u2014 schets en prototype naast elkaar",en:"Photo \u2014 sketch and prototype side by side"}
  },
  howh:{nl:"Hoe het werkt",en:"How it works"},
  howd:{nl:"Vier stappen, en u zit pas na stap drie ergens aan vast.",
        en:"Four steps, and you're not committed to anything until after step three."},
  how:[
    {ic:"web", h:{nl:"U stuurt twee zinnen",en:"You send two sentences"},
     dw:"layout", note:{nl:"Foto — het formulier op een telefoon",en:"Photo — the form on a phone"},
     p:{nl:"Via het formulier of per mail. Geen briefing, geen aanbestedingsdocument \u2014 wat er moet gebeuren en wanneer. Binnen drie werkdagen antwoord, en binnen een week een afspraak.",
        en:"Through the form or by email. No briefing document, no tender \u2014 what needs to happen and by when. A reply within three working days, and a meeting within a week."}},
    {ic:"test", h:{nl:"Een half uur, gratis",en:"Half an hour, free"},
     dw:"bench", note:{nl:"Foto — een gesprek aan tafel",en:"Photo — a conversation at the table"},
     p:{nl:"Videocall of bij u op locatie, met de engineer die het werk zou doen. Wij stellen vragen, u krijgt een eerlijk oordeel \u2014 ook als dat \u2018hier zijn wij niet de juiste partij voor\u2019 is.",
        en:"Video call or at your site, with the engineer who would do the work. We ask questions, you get an honest verdict \u2014 including \u2018we are not the right party for this\u2019."}},
    {ic:"cad", h:{nl:"Een voorstel van \u00e9\u00e9n pagina",en:"A one-page proposal"},
     dw:"rule", note:{nl:"Render — het voorstel van \u00e9\u00e9n pagina",en:"Render — the one-page proposal"},
     p:{nl:"Een pdf met scope, vaste prijs, planning en wat er niet in zit. Geen bijlage van dertig pagina\u2019s. U beslist op die ene pagina.",
        en:"A PDF with scope, fixed price, timeline and what is not included. No thirty-page appendix. You decide on that one page."}},
    {ic:"dfm", h:{nl:"We bouwen, u ziet het groeien",en:"We build, you watch it grow"},
     dw:"printer", note:{nl:"Foto — het werk in uitvoering",en:"Photo — the work in progress"},
     p:{nl:"Korte updates met foto\u2019s van wat er af is. Meerwerk gaat alleen door als u er vooraf ja op zegt.",
        en:"Short updates with photos of what is finished. Extra work only proceeds if you say yes to it in advance."}}
  ],
  ctasub:{nl:"Geen briefing nodig. Twee zinnen is genoeg om te beginnen.",
          en:"No briefing needed. Two sentences is enough to start."},
  whoh:{nl:"Wie we zijn", en:"Who we are"},
  teamh:{nl:"Het team", en:"The team"},
  teamd:{nl:"We zijn alle vier mechatronicus — dit zijn alleen de specialismen. U spreekt degene die uw werk doet.",
         en:"All four of us are mechatronics engineers — these are just the specialisms. You speak to the one doing your work."},
  /* `img` names a file in assets/renders/. Swap the four filenames around to change who
     sits under which role — nothing else has to move. Portraits are 4:5. */
  team:[
    {img:"team-1", n:{nl:"Naam",en:"Name"}, r:{nl:"Software & web — automatisering, AI, en uw eerste aanspreekpunt",en:"Software & web — automation, AI, and your first point of contact"}},
    {img:"team-2", n:{nl:"Naam",en:"Name"}, r:{nl:"Leiding & hardware — planning, inkoop, bouw",en:"Operations & hardware — planning, sourcing, build"}},
    {img:"team-3", n:{nl:"Naam",en:"Name"}, r:{nl:"Besturingstechniek — machinebesturing, sensoren, meten",en:"Control engineering — machine control, sensors, measurement"}},
    {img:"team-4", n:{nl:"Naam",en:"Name"}, r:{nl:"CAD & elektronica — mechanica, PCB, 3D-print",en:"CAD & electronics — mechanics, PCB, 3D print"}}
  ],
  teamwork:{nl:"Bekijk ons werk", en:"See our work"},
  teamabout:{nl:"Over ons", en:"About us"},
  whoq:{nl:"Vier engineers, zes vakgebieden. U legt het probleem één keer uit, aan de mensen die het bouwen.",
        en:"Four engineers, six disciplines. You explain the problem once, to the people who will build it."},
  whop:{nl:"We komen uit het Brabantse bedrijfsleven en van Fontys: software, web, mechanica, elektronica, besturing en drones. Voor u betekent dat in feite \u00e9\u00e9n aanspreekpunt dat alles kan \u2014 u hoeft niet zelf uit te zoeken welke discipline uw vraag is, en niets valt tussen twee leveranciers in.\n\nWe leiden studenten op terwijl ze aan echt werk werken. Dat is deels overtuiging en deels rekenkunde: Brabant heeft te weinig technische mensen, en er zijn maar twee manieren om daaraan iets te doen.",
        en:"We come from working in Noord-Brabant's industry and from Fontys: software, web, mechanics, electronics, control and drones. For you it works like one person who can do everything \u2014 you don't have to work out which discipline your question belongs to, and nothing falls between two suppliers.\n\nWe train students on real work. That is part conviction and part arithmetic: Brabant is short of technical people, and there are only two ways to change that."},
  stats:[
    {n:"4", k:{nl:"engineers, plus studenten die meebouwen",en:"engineers, plus students who build with us"}},
    {n:"1", k:{nl:"werkdag tot antwoord van de engineer zelf",en:"working day to a reply from the engineer"}},
    {n:"2026", k:{nl:"opgericht in 's-Hertogenbosch",en:"founded in 's-Hertogenbosch"}}
  ],
  photo1:{nl:"Foto — het team aan het werk",en:"Photo — the team at work"},
  photo1s:{nl:"Breed, handen en machines in beeld · 16:9",en:"Wide, hands and machines in shot · 16:9"},
  photo2:{nl:"Foto — iemand aan het werk",en:"Photo — someone working"},
  photo2s:{nl:"Staand portret · 3:4",en:"Portrait · 3:4"},
  clientsh:{nl:"Klanten & partners", en:"Clients & partners"},
  clientsd:{nl:"Logo's komen hier zodra we toestemming hebben. Onder geheimhouding werken we ook aan detectie- en besturingstechniek.",
            en:"Logos go here once we have permission. Under NDA we also work on detection and control engineering."},
  logos:["HUTKO Kitchen","МАКС Автосервіс",{nl:"Logo klant 3",en:"Client logo 3"},{nl:"Logo partner",en:"Partner logo"},{nl:"Logo partner",en:"Partner logo"}],
  ctah:{nl:"Een concreet probleem? Stuur het in twee zinnen.", en:"Got a concrete problem? Send it in two sentences."},
  ctab:{nl:"Neem contact op", en:"Get in touch"}
},
foot:{
  seo:{nl:"Liminex is een engineeringbureau in 's-Hertogenbosch. Wij bouwen websites en webshops, doen AI-automatisering, en ontwikkelen prototypes: mechanica, elektronica, PCB-ontwerp, firmware, besturingstechniek, robotica, drones en CAD. Kleine series maken we zelf met 3D-printen, lasersnijden en CNC. Actief in Noord-Brabant \u2014 's-Hertogenbosch, Eindhoven, Tilburg, Breda \u2014 en de rest van Nederland.",
       en:"Liminex is an engineering firm in 's-Hertogenbosch, the Netherlands. We build websites and online shops, do AI automation, and develop prototypes: mechanics, electronics, PCB design, firmware, control engineering, robotics, drones and CAD. Short runs we make ourselves with 3D printing, laser cutting and CNC. Working across Noord-Brabant \u2014 's-Hertogenbosch, Eindhoven, Tilburg, Breda \u2014 and the rest of the Netherlands."},
  formh:{nl:"Stuur ons twee zinnen",en:"Send us two sentences"},
  formd:{nl:"Vertel kort wat er moet gebeuren. U krijgt binnen drie werkdagen antwoord van de engineer die het zou doen \u2014 ook als dat antwoord \u2018dit past niet bij ons\u2019 is \u2014 en binnen een week een afspraak.",
         en:"Tell us briefly what needs to happen. You'll hear back within three working days from the engineer who would do it \u2014 including if the answer is \u2018this isn't for us\u2019 \u2014 and have a meeting within a week."},
  work:{nl:"Werk",en:"Work"}, more:{nl:"Meer",en:"More"}, contact:{nl:"Contact",en:"Contact"},
  legal:{nl:"Richtprijzen staan op de tarievenpagina",en:"Indicative prices are on the pricing page"}},
about:{
  lede:{nl:"Software \u00e9n hardware in \u00e9\u00e9n team in 's-Hertogenbosch \u2014 zodat uw project niet opgeknipt wordt.",
        en:"Software and hardware in one team in 's-Hertogenbosch \u2014 so your project never gets split up."},
  storyh:{nl:"Hoe het begon", en:"How it started"},
  wayh:{nl:"Hoe we werken", en:"How we work"},
  way:[
    {h:{nl:"U spreekt de engineer",en:"You speak to the engineer"},
     p:{nl:"Geen accountmanager tussen u en het werk. Degene die het bouwt zit bij het gesprek.",
        en:"No account manager between you and the work. Whoever builds it is in the conversation."}},
    {h:{nl:"Eerst een pagina, dan pas bouwen",en:"One page first, then build"},
     p:{nl:"Scope, prijs en planning op één pagina voordat er iets gemaakt wordt. Geen prijslijst — elk project is anders.",
        en:"Scope, price and timeline on one page before anything is made. No price list — every project differs."}},
    {h:{nl:"We zeggen het als het niet past",en:"We say so when it doesn't fit"},
     p:{nl:"Kleine series maken we hier; grote aantallen in India of lokaal, en we rekenen voor wanneer dat níet loont.",
        en:"Small runs we make here; large volumes in India or locally, and we do the maths on when that is not worth it."}},
    {h:{nl:"Studenten bouwen mee",en:"Students build with us"},
     p:{nl:"Onder begeleiding, op echt werk. Dat houdt onze tarieven redelijk en leidt mensen op die Brabant nodig heeft.",
        en:"Supervised, on real work. It keeps our rates reasonable and trains the people Brabant needs."}}
  ],
  kith:{nl:"Wat er in huis staat", en:"What is in the building"},
  kit:[
    {h:{nl:"3D-printers",en:"3D printers"},p:{nl:"Functionele onderdelen, jigs en behuizingen in kunststof.",en:"Functional parts, jigs and enclosures in plastic."}},
    {h:{nl:"Lasersnijder",en:"Laser cutter"},p:{nl:"Plaatwerk, panelen en frontplaten, snel van tekening naar deel.",en:"Sheet parts, panels and front plates, quickly from drawing to part."}},
    {h:{nl:"CNC (klein)",en:"CNC (small)"},p:{nl:"Aluminium en kunststof onderdelen waar print te zwak is.",en:"Aluminium and plastic parts where printing is too weak."}},
    {h:{nl:"Elektronicabank",en:"Electronics bench"},p:{nl:"Solderen, meten en testen van besturing en sensoren.",en:"Soldering, measuring and testing control and sensors."}}
  ]
},
folio:{
  h:{nl:"Werk dat live staat", en:"Work that is live"},
  exph:{nl:"Ervaring", en:"Experience"},
  expd:{nl:"Wat we op dit terrein al hebben opgeleverd.", en:"What we have already delivered in this area."},
  d:{nl:"Twee opgeleverde projecten, allebei nog in gebruik.", en:"Two delivered projects, both still in use."},
  next:{nl:"Wilt u de volgende zijn?", en:"Would you like to be next?"},
  nextp:{nl:"Vertel in twee zinnen wat er moet gebeuren. Wij zeggen eerlijk of het bij ons past.",
         en:"Tell us in two sentences what needs to happen. We'll say honestly whether it suits us."}
},
web:{
  lede:{nl:"U stelt het zich voor, wij vinden samen de beste uitvoering. Website, webshop, app, AI, SEO of iets dat nog geen naam heeft.",
        en:"You imagine it, we find the best execution together. Website, online shop, app, AI, SEO, or something that doesn't have a name yet."},
  intro:{nl:"We beginnen niet bij de techniek maar bij uw klant: wat moet iemand bij u kunnen ervaren, boeken, bestellen of begrijpen? Daarna kiezen we samen wat daar het beste bij past \u2014 een website, een webshop, een app of webapp, een stuk AI in uw proces, betere vindbaarheid, of een combinatie. Vaak blijkt de eenvoudigste uitvoering de beste, en soms is het iets wat nog niemand voor u gebouwd heeft. Het is uw verbeelding en onze uitvoering.",
         en:"We don't start from the technology but from your customer: what should someone be able to experience, book, order or understand with you? Then we choose together what fits that best \u2014 a website, an online shop, an app or web app, a piece of AI in your process, better findability, or a mix. Often the simplest execution turns out to be the best one, and sometimes it is something nobody has built for you before. It is your imagination and our execution."},
  exhibh:{nl:"De tentoonstelling", en:"The exhibition"},
  exhibd:{nl:"Dit is wat we tot nu toe hebben opgeleverd. Beide sites staan live en worden nog gebruikt.",
          en:"This is what we have delivered so far. Both sites are live and still in use."},
  svcs:[
   {n:{nl:"Website of webshop",en:"Website or online shop"},
    d:{nl:"Van één pagina tot een tweetalige site met een echt contentsysteem dat u zelf bedient. Snel, vindbaar, en elke site die wij opleveren voldoet aan WCAG 2.1 AA — we draaien die test op onze eigen site ook, voor elke wijziging.",
       en:"From a single page to a bilingual site with a real content system you run yourself. Fast, findable, and every site we deliver meets WCAG 2.1 AA — we run that test on our own site too, before every change."}},
   {n:{nl:"Boeken, betalen en klantaccounts",en:"Booking, payments and customer accounts"},
    d:{nl:"Afspraken, tijdsloten, aanbetalingen, iDEAL en kaart. Het komt in uw agenda en op uw rekening, niet in het dashboard van een derde partij dat u twee keer per dag moet controleren.",
       en:"Appointments, slots, deposits, iDEAL and card. It lands in your calendar and your bank account — not in a third party's dashboard you have to check twice a day."}},
   {n:{nl:"Het stuk dat nergens kant-en-klaar bestaat",en:"The part that comes in no box"},
    d:{nl:"Een app, een webapp, een configurator, een klantportaal, een offertecalculator, een voorraadscherm aan de muur. Precies het ding dat een standaardplatform niet kan — en meestal ook precies het ding waarin u van uw concurrent verschilt.",
       en:"An app, a web app, a configurator, a customer portal, a quote calculator, a stock screen on the wall. Exactly the thing an off-the-shelf platform cannot do — and usually exactly the thing that makes you different from your competitor."}},
   {n:{nl:"Een ontwerp dat van u is",en:"A design that is actually yours"},
    d:{nl:"Geen sjabloon met uw logo in de hoek. Kleur, typografie en indeling gebouwd rond wat uw bedrijf werkelijk is, zodat een bezoeker u kan onderscheiden van de vier andere tabbladen die hij open heeft staan.",
       en:"Not a template with your logo dropped in the corner. Colour, type and layout built around what your company actually is, so a visitor can tell you apart from the four other tabs they have open."}},
   {n:{nl:"AI, automatisering en vindbaarheid",en:"AI, automation and findability"},
    d:{nl:"Één proces dat nu handwerk is en dat niet hoeft te zijn: offertes uit e-mail halen, facturen inlezen, post sorteren, rapportages die zichzelf maken. En SEO: gevonden worden door de mensen die u zoekt. We beginnen met wat u het meeste tijd of klanten kost.",
       en:"One process that is manual today and doesn't need to be: pulling quotes out of email, reading invoices, triaging messages, reports that write themselves. And SEO: being found by the people looking for you. We start with whatever costs you the most time or customers."}},
   {n:{nl:"Onderhoud",en:"Care"},
    d:{nl:"Updates, back-ups, monitoring en kleine wijzigingen, zodat de site over twee jaar nog werkt. Voor automatisering: bijsturen als uw proces verandert.",
       en:"Updates, backups, monitoring and small changes, so the site still works in two years. For automation: adjusting when your process changes."}}
  ],
  moreh:{nl:"Ook onderdeel van het werk",en:"Also part of the job"},
  steps:[
    {h:{nl:"Gesprek van een half uur",en:"A half-hour conversation"},p:{nl:"Wat moet het opleveren, en voor wie. Kost niets.",en:"What it has to achieve, and for whom. Costs nothing."}},
    {h:{nl:"Voorstel op één pagina",en:"A proposal on one page"},p:{nl:"Scope, prijs en planning, op maat. Geen verrassingen achteraf.",en:"Scope, price and timeline, made for you. No surprises afterwards."}},
    {h:{nl:"Bouwen, met u erbij",en:"We build, with you in the loop"},p:{nl:"U ziet het groeien en stuurt onderweg bij.",en:"You watch it grow and steer as we go."}},
    {h:{nl:"Live, en daarna onderhouden",en:"Live, then maintained"},p:{nl:"Overdracht, uitleg, en desgewenst onderhoud.",en:"Handover, training, and maintenance if you want it."}}
  ]
},
proto:{
  lede:{nl:"U heeft een idee. Vertel het ons, en wij bouwen het \u2014 van schets naar een werkend exemplaar dat u aan iemand kunt laten zien.",
        en:"You have an idea. Tell us, and we build it \u2014 from sketch to a working unit you can put in front of someone."},
  intro:{nl:"Het begint bij uw idee, niet bij onze specialisatie. Een apparaat, een meetopstelling, een machine die iets moet doen wat nog niets doet \u2014 u beschrijft wat het moet kunnen, wij vertalen dat naar mechanica, elektronica, firmware en besturing, in \u00e9\u00e9n team. Hieronder wat we precies doen en op welke terreinen.",
         en:"It starts with your idea, not with our specialism. A device, a measurement setup, a machine that has to do something nothing does yet \u2014 you describe what it must be able to do, we translate that into mechanics, electronics, firmware and control, in one team. Below: exactly what we do, and in which fields."},
  svcs:[
    {n:{nl:"Haalbaarheidssprint",en:"Feasibility sprint"},
     d:{nl:"Twee weken: kan het, wat kost het, waar zit het risico. Een technisch onderbouwd antwoord plus kostenraming, en een eerlijk advies om wel of niet door te gaan.",
        en:"Two weeks: can it be done, what will it cost, where is the risk. A technically grounded answer plus a cost estimate, and an honest recommendation on whether to continue."}},
    {n:{nl:"Prototype",en:"Prototype build"},
     d:{nl:"Behuizing, print en firmware tot een werkend exemplaar dat u kunt laten zien, testen en in handen van een klant geven.",
        en:"Enclosure, PCB and firmware to one working unit you can show, test and put in a customer's hands."}},
    {n:{nl:"Engineering-capaciteit",en:"Engineering capacity"},
     d:{nl:"Vaste uren per maand, voor bedrijven met structureel ontwikkelwerk en geen engineer. Of losse dagen als u alleen even handen nodig heeft.",
        en:"Fixed hours per month, for companies with steady development work and nobody to hire. Or single days when you just need hands."}}
  ],
  cardsh:{nl:"Wat we in huis doen", en:"What we do in-house"},
  cards:[
    {h:{nl:"Mechanica & CAD",en:"Mechanics & CAD"},p:{nl:"Constructie, behuizingen, jigs. Ontworpen om gemaakt te worden.",en:"Structures, enclosures, jigs. Designed to be manufacturable."}},
    {h:{nl:"Elektronica & firmware",en:"Electronics & firmware"},p:{nl:"Schema, printontwerp, embedded software in C en C++.",en:"Schematics, PCB layout, embedded software in C and C++."}},
    {h:{nl:"Besturing & robotica",en:"Control & robotics"},p:{nl:"Machinebesturing, aandrijving, meet- en regeltechniek.",en:"Machine control, drives, measurement and regulation."}},
    {h:{nl:"Data & simulatie",en:"Data & simulation"},p:{nl:"Python, meetdata, modellen. Uitrekenen wat er gebeurt voordat u bouwt.",en:"Python, measurement data, models. Working out what happens before you build."}}
  ]
},
india:{
  lbl:{nl:"Binnenkort",en:"Coming soon"},
  h:{nl:"Serieproductie in India",en:"Series production in India"},
  p:{nl:"We zijn een route naar Indiase fabrikanten aan het opzetten voor klanten die naar grotere aantallen gaan. Nog niet live \u2014 we willen eerst weten of er vraag naar is voordat we er tijd in steken.\n\nInteresse? Eén klik, en uw e-mailadres als u bericht wilt wanneer het zover is. Verder niets.",
     en:"We are setting up a route to Indian manufacturers for clients moving to larger volumes. Not live yet \u2014 we want to know whether there is demand before we put time into it.\n\nInterested? One click, plus your email address if you want to hear when it is ready. Nothing else."},
  btn:{nl:"Ja, hier heb ik interesse in",en:"Yes, I'd be interested"},
  mailph:{nl:"uw e-mailadres (optioneel)",en:"your email address (optional)"},
  send:{nl:"Doorgeven",en:"Register interest"},
  ok:{nl:"Genoteerd, dank u. We laten het weten zodra dit er is.",
      en:"Noted, thank you. We'll let you know when this is ready."},
  okq:{nl:"Genoteerd \u2014 zonder e-mailadres, dus we tellen u mee maar kunnen u niet bereiken.",
       en:"Noted \u2014 without an email address, so you're counted but we can't reach you."},
  fail:{nl:"Doorgeven lukte niet. Mail ons gerust rechtstreeks.",
        en:"That didn't register. Feel free to email us directly."},
  already:{nl:"U heeft hier al interesse in doorgegeven. Dank.",en:"You've already registered interest. Thank you."}
},
make:{
  lede:{nl:"Eerst hier maken, dan pas opschalen. Wij zijn eerlijk over waar dat omslagpunt ligt.",
        en:"Make it here first, scale it later. We're honest about where that tipping point is."},
  intro:{nl:"Met een 3D-printer, lasersnijder en CNC in huis maken we kleine series direct hier — geen minimale afname, geen wachttijd, en u kunt tussentijds nog wijzigen. Voor grotere aantallen brengen we u in contact met producenten in Nederland en India, en begeleiden we het traject.",
         en:"With a 3D printer, laser cutter and CNC in the building we make small runs here — no minimum order, no lead time, and you can still change something halfway. For larger volumes we connect you with manufacturers in the Netherlands and India, and manage the process."},
  machh:{nl:"De machines in huis",en:"The machines in the building"},
  machd:{nl:"Alle drie staan in 's-Hertogenbosch. Geen minimale afname, geen wachtrij bij een externe partij, en u kunt halverwege nog iets veranderen.",
         en:"All three are here in 's-Hertogenbosch. No minimum order, no queue at an outside supplier, and you can still change something halfway."},
  machines:[
    {key:"machine-print3d",
     n:{nl:"3D-printen",en:"3D printing"},
     d:{nl:"Uw bestand erin, en het onderdeel groeit laag voor laag, meestal 's nachts. Behuizingen, mallen, beugels en vormen waar een frees fysiek niet bij kan. Geen matrijskosten, dus \u00e9\u00e9n stuk kost wat \u00e9\u00e9n stuk kost \u2014 en een wijziging morgen is een nieuwe print, geen nieuwe mal.",
        en:"Your file goes in and the part grows layer by layer, usually overnight. Housings, jigs, brackets, and shapes a mill physically cannot reach. No tooling, so one part costs what one part costs \u2014 and a change tomorrow is a new print, not a new mould."},
     shot:{nl:"Foto \u2014 de 3D-printer aan het werk",en:"Photo \u2014 the 3D printer running"}},
    {key:"machine-laser",
     n:{nl:"Lasersnijden",en:"Laser cutting"},
     d:{nl:"Plaatmateriaal, in minuten op tekening gesneden. Panelen, pakkingen, frontplaten, beugels en behuizingsdelen die daarna gezet worden. De snelste weg van tekening naar iets dat u vast kunt houden \u2014 daarom begint het meeste werk hier.",
        en:"Flat sheet, cut to the drawing in minutes. Panels, gaskets, front plates, brackets and enclosure parts that get folded afterwards. The fastest route from a drawing to something you can hold, which is why most work starts here."},
     shot:{nl:"Foto \u2014 de lasersnijder in bedrijf",en:"Photo \u2014 the laser cutter at work"}},
    {key:"machine-cnc",
     n:{nl:"CNC-frezen",en:"CNC milling"},
     d:{nl:"Als een geprint onderdeel niet stijf of nauwkeurig genoeg is: dezelfde geometrie uit massief aluminium of kunststof. Opnames die kracht dragen, delen die om een lager moeten passen, alles dat gebruikt wordt in plaats van getoond.",
        en:"For when a printed part is not stiff or accurate enough: the same geometry cut from solid aluminium or plastic. Mounts that carry load, parts that have to fit a bearing, anything that has to survive being used rather than shown."},
     shot:{nl:"Foto \u2014 de CNC-frees met een opspanning",en:"Photo \u2014 the CNC mill with a part clamped"}}
  ],
  aroundh:{nl:"En daaromheen",en:"And around them"},
  svcs:[
    {n:{nl:"Ontwerp + maken",en:"Design + make"},
     d:{nl:"U heeft een probleem, wij leveren het onderdeel. Een schets of foto is genoeg om te beginnen.",en:"You have a problem, we deliver the part. A sketch or a photo is enough to start."}},
    {n:{nl:"Klaarmaken voor serie",en:"Ready for series"},
     d:{nl:"Uw ontwerp geschikt maken voor serieproductie, leveranciers zoeken en beoordelen, monsters laten maken en de kwaliteit controleren.",
        en:"Getting your design ready for series production, finding and vetting suppliers, running samples and checking quality."}},
    {n:{nl:"Inkoopbegeleiding",en:"Sourcing"},
     d:{nl:"Wij regelen de productie en de kwaliteitscontrole. U blijft zelf importeur van de goederen — dat scheelt u niets in kwaliteit en ons allebei een hoop juridische rompslomp.",
        en:"We manage production and quality control. You remain importer of record — it costs you nothing in quality and saves us both a great deal of legal trouble."}}
  ],
  },
yard:{
  lede:{nl:"Een plek in Noord-Brabant waar bedrijven, studenten en makers samen techniek bouwen. We onderzoeken nu of er genoeg vraag is.",
        en:"A place in Noord-Brabant where companies, students and makers build technology together. We're testing whether the demand is really there."},
  postersh:{nl:"Waarom we dit onderzoeken", en:"Why we are testing this"},
  posters:[
    {c:"p1", fig:"25,1%", say:{nl:"van alle Nederlandse R&D-investering komt uit Noord-Brabant. In Brainport is 68% daarvan van vijf bedrijven.",
        en:"of all Dutch R&D investment comes from Noord-Brabant. In Brainport, 68% of it belongs to five companies."},
     src:{nl:"Brainport Monitor · CBS StatLine 84985NED",en:"Brainport Monitor · CBS StatLine 84985NED"}},
    {c:"p2", fig:"14%", say:{nl:"van de bedrijven met 2–10 medewerkers gebruikt AI. Bij bedrijven met 250+ is dat 66%.",
        en:"of firms with 2–10 staff use AI. Among firms with 250+ it is 66%."},
     src:{nl:"CBS, 2025",en:"CBS, 2025"}},
    {c:"p3", fig:"73%", say:{nl:"noemt gebrek aan ervaring als reden om geen AI te gebruiken. Niet geld. Niet techniek. Ervaring.",
        en:"name lack of experience as the reason they didn't adopt AI. Not money. Not technology. Experience."},
     src:{nl:"CBS, 2025",en:"CBS, 2025"}},
    {c:"p4", fig:"50.000", say:{nl:"technische mensen tekort in Brainport over tien jaar. Het onderwijs levert er 20.000 van de 70.000.",
        en:"technical people short in Brainport over ten years. Education supplies 20,000 of the 70,000 needed."},
     src:{nl:"Brainport",en:"Brainport"}}
  ],
  introh:{nl:"Wat het zou zijn", en:"What it would be"},
  intro:{nl:"Een werkplaats met machines, ruimte en begeleiding: open voor mkb'ers met een idee, studenten die iets willen bouwen en makers zonder eigen werkplaats. In Brabant staan 22.805 bedrijven met twee of meer medewerkers in de sectoren waar wij werken — bijna allemaal te klein om zelf een engineer in dienst te nemen. Tegelijk studeren er meer dan 30.000 techniek- en ICT-studenten in de provincie. Die twee groepen ontmoeten elkaar nu nauwelijks.",
         en:"A workshop with machines, space and guidance: open to SME owners with an idea, students who want to build something, and makers without a workshop of their own. Brabant has 22,805 businesses with two or more staff in the sectors we work in — nearly all too small to employ an engineer. At the same time more than 30,000 engineering and ICT students are studying in the province. Those two groups barely meet."},
  cardsh:{nl:"Voor wie het is", en:"Who it is for"},
  cards:[
    {h:{nl:"Voor bedrijven",en:"For companies"},p:{nl:"Machinetijd, een plek om te testen, en engineers om mee te sparren.",en:"Machine time, somewhere to test, and engineers to think out loud with."}},
    {h:{nl:"Voor studenten",en:"For students"},p:{nl:"Echt werk aan echte opdrachten, betaald, naast je studie.",en:"Real work on real projects, paid, alongside your studies."}},
    {h:{nl:"Voor makers",en:"For makers"},p:{nl:"Toegang tot machines die je thuis niet hebt, en mensen die weten hoe ze werken.",en:"Access to machines you don't have at home, and people who know how to use them."}}
  ],
  formh:{nl:"Doe mee aan het onderzoek", en:"Take part in the survey"},
  formd:{nl:"Vier minuten. Geen account nodig. Uw antwoord bepaalt of dit er komt, waar het komt en wat het gaat kosten — en of we het klein beginnen of groot.",
         en:"Four minutes. No account needed. Your answer decides whether this happens, where, what it will cost — and whether we start small or large."},
  formnl:{nl:"Nederlandse vragenlijst",en:"Dutch questionnaire"},
  formen:{nl:"English questionnaire",en:"English questionnaire"},
  formnls:{nl:"Voor ondernemers, studenten en makers in Noord-Brabant.",en:"For entrepreneurs, students and makers in Noord-Brabant."},
  formens:{nl:"Dezelfde vragen, in het Engels.",en:"The same questions, in English."},
  open:{nl:"Vragenlijst openen",en:"Open the questionnaire"},
  statush:{nl:"Waar het nu staat", en:"Where this stands"},
  status:{nl:"We zoeken ruimte en financiering, en peilen eerst of er genoeg vraag is voordat we iets huren. Bent u ondernemer, student of maker in Noord-Brabant? Vul de vragenlijst in — dat is op dit moment het nuttigste wat u kunt doen.",
          en:"We're looking for space and funding, and testing whether the demand is really there before we rent anything. Are you an entrepreneur, student or maker in Noord-Brabant? Fill in the questionnaire — right now that is the most useful thing you can do."}
},
start:{
  lede:{nl:"U heeft een idee en geen technisch team. Wij zijn dat team, tot u er zelf een heeft.",
        en:"You have an idea and no technical team. We are that team, until you have your own."},
  intro:{nl:"De meeste startende ondernemers met een technisch product lopen op hetzelfde punt vast: ze kunnen het niet zelf bouwen, en een engineeringbureau dat voor grote bedrijven werkt is onbetaalbaar. Wij zitten daartussen. We beginnen klein en eerlijk — vaak met de vraag of het idee überhaupt kan.",
         en:"Most founders with a technical product hit the same wall: they can't build it themselves, and an engineering firm that works for corporates is out of reach. We sit in between. We start small and honestly — often with the question of whether the idea works at all."},
  svch:{nl:"Hoe wij dit betaalbaar maken",en:"How we make this affordable"},
  svcd:{nl:"Een startend bedrijf heeft zelden het budget van een bestaand bedrijf, en dat weten we. Vier dingen die we daarom anders doen dan bij onze andere klanten — alle vier op papier, voordat we beginnen.",
        en:"A company at the start rarely has the budget of an established one, and we know it. Four things we therefore do differently here than for our other clients — all four on paper before we begin."},
  svcs:[
   {n:{nl:"Betalen als het werkt",en:"Pay when it works"},
    d:{nl:"Een deel van het bedrag kan achter een mijlpaal: u betaalt wanneer er een werkend exemplaar staat, niet wanneer er een plan ligt. Het is geen gratis werk — we zetten de verdeling en de termijnen op één pagina — maar het betekent dat een goed idee niet strandt op de maand waarin u toevallig zit.",
       en:"Part of the fee can sit behind a milestone: you pay when there is a working unit, not when there is a plan. It is not free work — the split and the dates go on one page first — but it means a good idea does not die because of the month you happen to be in."}},
   {n:{nl:"Partnerschap in plaats van een factuur",en:"Partnership instead of an invoice"},
    d:{nl:"Voor een klein aantal projecten per jaar nemen we een deel van de betaling als belang in wat er gebouwd wordt: een aandeel in de omzet, of in het bedrijf zodra er een bedrijf is. We doen dit alleen waar we het product zelf zouden gebruiken, en we zeggen veel vaker nee dan ja.",
       en:"For a small number of projects a year we take part of the payment as a stake in what gets built: a share of revenue, or of the company once there is one. We only do this where we would use the product ourselves, and we say no far more often than yes."}},
   {n:{nl:"Uitgestelde betaling",en:"Postponed payment"},
    d:{nl:"Een afgesproken deel van de factuur later betalen \u2014 als de eerste omzet er is, of op een vaste datum die we vooraf afspreken. Geen rente, wel een handtekening.",
       en:"Pay an agreed part of the invoice later \u2014 once the first revenue is in, or on a fixed date we agree up front. No interest, but a signature."}},
   {n:{nl:"Steun die niet op de factuur staat",en:"Support that is not on the invoice"},
    d:{nl:"Een introductie bij een leverancier, een tweede mening over een offerte die u kreeg, een uur meedenken over uw pitch. Dat doen we voor de oprichters met wie we werken en het wordt niet gefactureerd — het kost ons een uur en het scheelt u een maand.",
       en:"An introduction to a supplier, a second opinion on a quote you were sent, an hour thinking along on your pitch. We do this for the founders we work with and it does not go on the bill — it costs us an hour and saves you a month."}}
  ],
  steps:[
    {h:{nl:"Klopt het idee technisch?",en:"Does the idea hold up technically?"},p:{nl:"Een eerlijk antwoord voordat u geld uitgeeft. Soms is dat 'nee', en dan zeggen we dat.",en:"An honest answer before you spend money. Sometimes it's no, and we'll say so."}},
    {h:{nl:"Wat kost het echt?",en:"What will it really cost?"},p:{nl:"Ontwikkeling, onderdelen, certificering, productie. Het volledige plaatje, niet alleen het leuke deel.",en:"Development, parts, certification, production. The whole picture, not just the fun part."}},
    {h:{nl:"Eén werkend exemplaar",en:"One working unit"},p:{nl:"Iets dat u kunt laten zien aan klanten en investeerders. Dat verandert gesprekken.",en:"Something you can show customers and investors. That changes conversations."}},
    {h:{nl:"En dan verder",en:"And then onward"},p:{nl:"Naar een kleine serie, of naar uw eigen team — wij dragen over en houden niets achter.",en:"To a small production run, or to your own team — we hand over and keep nothing back."}}
  ],
},
price:{
  lede:{nl:"Vaste prijzen voor websites en webshops. U weet wat het kost voordat u belt.",
        en:"Fixed prices for websites and online shops. You know what it costs before you call."},
  intro:{nl:"De meeste bureaus zeggen “neem contact op” en laten u raden. Wij zetten de prijs erbij. Past uw vraag niet in een pakket, dan krijgt u na één gesprek een vaste prijs op één pagina.",
         en:"Most agencies say “get in touch” and leave you guessing. We put the price on the page. If your question doesn't fit a package, you get a fixed price on one page after one conversation."},
  /* Launch discount. It switches itself off after `until` (end of that day, Dutch time),
     so the site never shows an expired offer. To end it early, set pct to 0. */
  promo:{pct:20, until:"2026-10-31",
         label:{nl:"Introductieprijs: 20% korting t/m 31 oktober 2026",en:"Launch price: 20% off until 31 October 2026"}},
  pkgh:{nl:"Websites en webshops",en:"Websites and online shops"},
  pkgs:[
    {n:"Start", v:950, from:false,
     d:{nl:["One-pager","Nederlands","Contactformulier","Mobiel-klaar","SEO-basis"],
        en:["One-pager","Dutch","Contact form","Mobile-ready","SEO basics"]}},
    {n:"MKB", v:2500, from:true,
     d:{nl:["Tot 5 pagina's","CMS — u past teksten zelf aan","SEO-basis","Nederlands"],
        en:["Up to 5 pages","CMS — you edit texts yourself","SEO basics","Dutch"]}},
    {n:"Webshop", v:4500, from:true,
     d:{nl:["WooCommerce of Shopify, op basis van een template","Betalingen","Producten ingericht"],
        en:["WooCommerce or Shopify, template-based","Payments","Product setup"]}}
  ],
  addh:{nl:"Uitbreidingen",en:"Add-ons"},
  adds:[
    {n:{nl:"Engelse versie",en:"English version"}, v:[200,400], of:{nl:["Start","MKB"],en:["Start","MKB"]}, disc:true},
    {n:{nl:"Extra pagina",en:"Extra page"}, v:[150], disc:true},
    {n:{nl:"Werk buiten de scope",en:"Out-of-scope work"}, v:[75], unit:{nl:"/ uur",en:"/ hour"}, disc:false}
  ],
  careh:{nl:"Care — hosting en onderhoud",en:"Care — hosting and upkeep"},
  cared:{nl:"Na oplevering houden wij de site draaiend. Per maand of per jaar, en bij een jaar is één maand gratis.",
         en:"After launch we keep the site running. Monthly or yearly, and a year gets you one month free."},
  care:{
    tiers:["S","M","L"],
    rows:[
      {k:{nl:"Per maand",en:"Monthly"}, v:[35,75,149], money:true},
      {k:{nl:"Per jaar (1 maand gratis)",en:"Yearly (1 month free)"}, v:[385,825,1639], money:true},
      {k:{nl:"Hosting, domein, SSL, back-ups, updates, uptime-bewaking",en:"Hosting, domain, SSL, backups, updates, uptime monitoring"}, v:[true,true,true]},
      {k:{nl:"Kleine wijzigingen inbegrepen",en:"Small edits included"},
       v:[{nl:"— (€75/uur)",en:"— (€75/h)"},{nl:"30 min/maand",en:"30 min/month"},{nl:"1 uur/maand",en:"1 h/month"}]},
      {k:{nl:"Reactietijd",en:"Response time"},
       v:[{nl:"3 werkdagen",en:"3 working days"},{nl:"2 werkdagen",en:"2 working days"},{nl:"1 werkdag",en:"1 working day"}]},
      {k:{nl:"Google Bedrijfsprofiel bijhouden",en:"Google Business Profile upkeep"}, v:[false,true,true]},
      {k:{nl:"Snelheids- en SEO-check per kwartaal + kort rapport",en:"Quarterly speed/SEO check + short report"}, v:[false,false,true]}
    ]},
  vat:{nl:"Alle bedragen zijn exclusief btw. De introductiekorting geldt voor de pakketten en uitbreidingen, niet voor Care of uurwerk.",
       en:"All amounts exclude VAT. The launch discount applies to packages and add-ons, not to Care or hourly work."},
  previewmore:{nl:"Uitbreidingen, Care-abonnementen en alle details",en:"Add-ons, Care plans and all the details"},
  fixh:{nl:"Van pakket naar live site",en:"From package to live site"},
  fix:[
    {h:{nl:"Twee zinnen",en:"Two sentences"},p:{nl:"U stuurt wat er moet gebeuren. Wij zeggen eerlijk of het bij ons past — soms is het antwoord nee.",en:"You send what needs to happen. We say honestly whether it suits us — sometimes the answer is no."}},
    {h:{nl:"Een half uur",en:"Half an hour"},p:{nl:"Gratis, met de engineer die het werk zou doen. Geen accountmanager.",en:"Free, with the engineer who'd do the work. No account manager."}},
    {h:{nl:"Eén pagina",en:"One page"},p:{nl:"Pakket, eventuele uitbreidingen en planning. Geen bijlagen van dertig pagina's.",en:"Package, any add-ons and timeline. No thirty-page appendix."}},
    {h:{nl:"Daarna pas rekenen",en:"Only then the bill"},p:{nl:"Meerwerk gaat alleen door als u er vooraf ja op zegt. Geen verrassingen achteraf.",en:"Extra work only proceeds if you say yes to it in advance. No surprises afterwards."}}
  ],
  noteh:{nl:"Iets anders dan een website?",en:"Something other than a website?"},
  note:{nl:"Prototypes, elektronica, automatisering en ander engineeringwerk begroten we per project — na één gesprek krijgt u een vaste prijs op één pagina.",
        en:"Prototypes, electronics, automation and other engineering work are priced per project — after one conversation you get a fixed price on one page."}
},

work:{
  lede:{nl:"Opgeleverd werk, nog in gebruik. Wilt u met een klant spreken, dan regelen we dat.",
        en:"Delivered work, still in use. If you want to speak to a client, we'll arrange it."},
  cases:[
    {t:"HUTKO Kitchen", img:"hutko", tag:{nl:"Website & webshop",en:"Website & online shop"}, url:"hutko-kitchen.com",
     short:{nl:"Oekraïens diepvriesmerk in Nederland. Wij bouwen en onderhouden de site, de webshop en de orderafhandeling.",en:"Ukrainian frozen food brand in the Netherlands. We build and maintain the site, the shop and order handling."},
     p:{nl:"HUTKO Kitchen maakt Oekraïense gerechten, vriest ze vers in en bezorgt door heel Nederland. Wij bouwden de website en de webshop: losse gerechten en samengestelde pakketten, bestellen met bezorging op donderdag en zaterdag tussen 16.00 en 21.00 uur, en een verhaal dat uitlegt waarom bevroren hier juist een voordeel is.",
        en:"HUTKO Kitchen makes Ukrainian dishes, freezes them fresh and delivers across the Netherlands. We built the website and the shop: individual dishes and ready-made boxes, ordering with delivery on Thursdays and Saturdays between 16:00 and 21:00, and a story that explains why frozen is an advantage rather than a compromise."},
     dl:[{k:{nl:"Wat we deden",en:"What we did"},v:{nl:"Ontwerp, bouw, webshop",en:"Design, build, online shop"}},
         {k:{nl:"Bijzonder",en:"Notable"},v:{nl:"Bezorging in vaste vensters door heel NL",en:"Fixed delivery windows nationwide"}},
         {k:{nl:"Status",en:"Status"},v:{nl:"Live en in gebruik",en:"Live and in use"}}]},
    {t:"МАКС Автосервіс", img:"maks", tag:{nl:"Website met online afspraken",en:"Website with online booking"}, url:"maksavtoservice.com",
     short:{nl:"Autoservice in Kyiv. Elke dienst met prijs én tijdsduur, en zelf een tijdslot kiezen.",en:"Car service in Kyiv. Every service with price and duration, and pick your own slot."},
     p:{nl:"Een autoservice in Kyiv die het anders wilde doen dan de rest van de branche: geen verrassingen op de rekening. Wij bouwden een tweetalige site (Oekraïens en Engels) waarop elke dienst met prijs én tijdsduur staat — olie verversen, computerdiagnose, banden, remmen, uitlijnen op 3D-apparatuur — plus een afsprakensysteem waarin de klant zelf een tijdslot kiest.",
        en:"A car service in Kyiv that wanted to work differently from the rest of the trade: no surprises on the bill. We built a bilingual site (Ukrainian and English) where every service is listed with its price and how long it takes — oil changes, computer diagnostics, tyres, brakes, 3D wheel alignment — plus a booking system where the customer picks their own time slot."},
     dl:[{k:{nl:"Wat we deden",en:"What we did"},v:{nl:"Ontwerp, bouw, afsprakensysteem, prijslijst",en:"Design, build, booking system, price list"}},
         {k:{nl:"Bijzonder",en:"Notable"},v:{nl:"Prijs én duur per dienst openbaar",en:"Price and duration published per service"}},
         {k:{nl:"Status",en:"Status"},v:{nl:"Live en in gebruik",en:"Live and in use"}}]}
  ],
  moreh:{nl:"Ook gedaan, nog niet openbaar", en:"Also delivered, not yet public"},
  morep:{nl:"Een deel van ons werk valt onder geheimhouding — onder andere in detectie- en besturingstechniek. In een gesprek kunnen we op hoofdlijnen vertellen wat we daar gedaan hebben.",
         en:"Some of our work is under NDA — including detection and control engineering. In a conversation we can describe at a high level what we did."}
},
contact:{
  lede:{nl:"Vertel in twee zinnen wat er moet gebeuren. U krijgt binnen drie werkdagen antwoord van de engineer die het zou doen, en binnen een week een afspraak.",
        en:"Tell us in two sentences what needs to happen. You'll hear back within three working days from the engineer who'd do it, and have a meeting within a week."},
  fields:{name:{nl:"Naam",en:"Name"},company:{nl:"Bedrijf",en:"Company"},email:{nl:"E-mail",en:"Email"},
    phone:{nl:"Telefoon",en:"Phone"},
    type:{nl:"Waar gaat het over",en:"What is it about"},
    budget:{nl:"Budget in gedachten",en:"Budget in mind"},
    when:{nl:"Wanneer moet het klaar zijn",en:"When does it need to be ready"},
    found:{nl:"Hoe kwam u bij ons terecht",en:"How did you find us"},
    msg:{nl:"Wat moet er gebeuren",en:"What needs to happen"},
    send:{nl:"Verzenden",en:"Send"},
    reqnote:{nl:"* verplicht",en:"* required"}},
  budgets:{nl:["Weet ik nog niet","Tot \u20ac1.500","\u20ac1.500 \u2013 5.000","\u20ac5.000 \u2013 15.000","Meer dan \u20ac15.000","Doorlopend per maand"],
           en:["Not sure yet","Up to \u20ac1,500","\u20ac1,500 \u2013 5,000","\u20ac5,000 \u2013 15,000","More than \u20ac15,000","Ongoing, per month"]},
  whens:{nl:["Geen harde deadline","Binnen een maand","Binnen drie maanden","Dit jaar","Er is een vaste datum"],
         en:["No hard deadline","Within a month","Within three months","This year","There is a fixed date"]},
  founds:{nl:["Google","LinkedIn","Doorverwezen door iemand","Een evenement of beurs","Anders"],
          en:["Google","LinkedIn","Referred by someone","An event or fair","Other"]},
  types:{nl:["Website of webshop","AI / automatisering","Prototype of engineering","Besturing van een machine","Onderdeel laten maken","Serieproductie / inkoop","Project Yard","Start-up: idee toetsen","Iets anders"],
         en:["Website or online shop","AI / automation","Prototype or engineering","Machine control","Get a part made","Production / sourcing","Project Yard","Start-up: test an idea","Something else"]},
  hp:{nl:"Laat dit veld leeg",en:"Leave this field empty"},
  sending:{nl:"Versturen\u2026",en:"Sending\u2026"},
  ok:{nl:"Verstuurd. U krijgt binnen drie werkdagen antwoord van de engineer die het zou doen.",
      en:"Sent. You'll hear back within three working days, from the engineer who'd do it."},
  fail:{nl:"Het versturen lukte niet \u2014 een adblocker of bedrijfsnetwerk blokkeert soms dit soort formulieren. Uw tekst is niet weg:",
        en:"That didn't send \u2014 an ad blocker or a corporate network sometimes blocks forms like this. Your text isn't lost:"},
  need:{nl:"Vul uw e-mailadres en uw bericht in.",en:"Please fill in your email address and your message."},
  privacy:{nl:"Wat u hier invult gebruiken we alleen om te antwoorden. We bewaren het niet langer dan nodig en geven het niet door.",
           en:"What you enter here is used only to reply. We don't keep it longer than needed and don't pass it on."},
  formnote:{nl:"Dit formulier is nog niet aangesloten — in de live site komen de berichten binnen op anastasiia@liminex.net.",
            en:"This form is not wired up yet — on the live site messages arrive at anastasiia@liminex.net."},
  details:[
    {k:{nl:"E-mail",en:"Email"},v:"anastasiia@liminex.net"},
    {k:{nl:"Werkgebied",en:"We work across"},v:{nl:"'s-Hertogenbosch en heel Noord-Brabant",en:"'s-Hertogenbosch and all of Noord-Brabant"}},
    {k:{nl:"KvK",en:"Chamber of Commerce"},v:"42104253"},
    {k:{nl:"Talen",en:"Languages"},v:{nl:"Nederlands, Engels, Oekraïens, Russisch, Hindi, Punjabi, Indonesisch",en:"Dutch, English, Ukrainian, Russian, Hindi, Punjabi, Indonesian"}}
  ]
}
};
